### ISSUE TITLE
Page that allows user to add or edit a book rating

### ISSUE THREAD

**Issue by aetherfaye1009** [angulardevelopment/book-rating-app-assignment#11]
What you will get : 

- Page that is ready to be either rate the book rating or update the existing book ratings
- Input contains of : title, author, publisher, published date, edition, summary/description, page count, ratings, review, review date.
- Save and Update function

P.S. No server-side interaction or external API calls

**Comment by aetherfaye1009** [comment]
Please assign me hacktoberfest tag if you are okay with it. Thank you.

**Comment by sunny7899** [comment]
Go ahead @aetherfaye1009
