### ISSUE TITLE
Implement Login and Signup Pages 

### ISSUE THREAD

**Issue by Maryann-01** [angulardevelopment/book-rating-app-assignment#16]
Implement the login and signup functionality for user authentication on the frontend. The login and signup pages will connect to the existing backend authentication routes.

**Comment by Maryann-01** [comment]
@sunny7899 , please assign this issue to me under hacktoberfest.
Also, this project is under angular dev but I can see the frontend code was written in React. Can I continue with React ?

**Comment by sunny7899** [comment]
go ahead @Maryann-01  yeah i will move it to the react organization.
