### ISSUE TITLE
I want to add a feature of fetching books from google books api when searched in search bar 

### ISSUE THREAD

**Issue by Shreya-1305** [angulardevelopment/book-rating-app-assignment#28]
When user will search for a particular book from the search bar in the navbar . It will display all the books with that particular keyord in it. and display on the screen . 

Please assign thi issue to me . Thankyou !

**Comment by sunny7899** [comment]
Great Go ahead @Shreya-1305

**Comment by Shreya-1305** [comment]
@sunny is this project also part of girlscript ? can you please add a label of girlscript-ext ?

**Comment by Shreya-1305** [comment]
I am sorry for delay . I will try finish working on this issue by tonight. Thankyou!
