### ISSUE TITLE
Creating a basic structure for contributors to start working on the project.

### ISSUE THREAD

**Issue by okay-pa1** [angulardevelopment/book-rating-app-assignment#3]
Description:
This will be a MERN stack based web app. 

Frontend:
Will be using React js to make the interface of the app.
Backend:
Express JS to define the routes, CRUD Operations and keep all the serverside logic.

**Comment by archita-2810** [comment]
I can work on the frontend by using ReactJS or NextJS @sunny7899

**Comment by sunny7899** [comment]
Go ahead @okay-pa1

**Comment by sunny7899** [comment]
@archita-2810 after structure is creating by @okay-pa1  you can start work on it. so create a task for it

**Comment by okay-pa1** [comment]
@archita-2810 I'll raise a PR when I'm done with this issue. After merging u can raise an issue and work on the frontend. Also, if u can use discord to communicate it would be very helpful. You can easily communicate with other interested contributors.

**Comment by okay-pa1** [comment]
@sunny7899 please add the hacktober fest accepted label when you are closing this issue. Thank you.
